version: '3'
services:
  web:
    container_name: jjb
    build: .
    ports:
    - "127.0.0.1:${HOST_HTTP_PORT}:80"
    - "127.0.0.1:443:443"
    environment:
    - XDEBUG_MODE=${XDEBUG_MODE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
    # - .:/jjb
    - ..:/var/www/html
    - /tmp/xdebug-profiles:/tmp/xdebug-profiles
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    container_name: jjb_db
    image: mariadb:10.5
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data_jjb:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: jjb_pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${HOST_PMA_PORT}:80
volumes:
  db_data_jjb:

